---
- hosts: all
  gather_facts: yes
  become: yes
  vars:
    NODEJS_VERSION: "8"
    ansible_distribution_release: "xenial" #trusty
  tasks:
    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes

    - name: Install the nodejs
      apt:
        name: nodejs
        state: present

    - name: Install the nginx
      apt:
        name: nginx
        state: present

    - name: start nginx
      service:
          name: nginx
          state: started

    - name: install NPM
      apt:
        name: npm 
        state: latest

    - name: Install PM2
      command: chdir=/root/ npm install pm2 -g      
    
    - name: Ansible create file if it doesn't exist example
      file:
        path: "/root/nodejs_ankur"
        state: touch
     
    - name: copy content
      copy:
        dest: "/root/index.js"
        content: const http = require('http');

           const hostname = 'localhost';
           const port = 3000;

           const server = http.createServer((req, res) => {
           res.statusCode = 200;
           res.setHeader('Content-Type', 'text/plain');
           res.end('this is my node website with ansible');
           });

           server.listen(port, hostname, () => {
           console.log(`Server running at http://${hostname}:${port}/`);
           });
    - name: start nodejs
      command: pm2 start index.js

